// The one puzzle the demo board shows, until the game API exists (Phase 5).
//
// Givens only. The solution is not here and must never be: in the real game
// it stays on the server (SECURITY.md), and the demo keeps the same shape.
//
// It lives in the bundle rather than behind an endpoint on purpose. Q13 says a
// puzzle is never visible outside a game session, and API.md lists
// `GET /api/puzzles/{id}` as deliberately absent. A throwaway endpoint serving
// puzzles would be exactly that, so the demo does without one. In Phase 6 the
// board gets its givens from `POST /api/games` instead, and this file goes.
//
// Generated by the engine, reproducible with:
//
//     cd backend && PYTHONPATH=src python -m sudoku generate --difficulty easy --seed 2026
//
// easy (hardest technique: hidden single), 25 clues, unique solution,
// generator v1.

export const DEMO_GIVENS =
  "700000002090400500120000000009803006073609040008100090057000200000900060000008000";
